version: "3.3"
services:
  cloudflare-ddns-ipv4:
    image: oznu/cloudflare-ddns
    container_name: cloudflare-ddns-ipv4
    restart: unless-stopped
    network_mode: host
    environment:
      - RRTYPE=A
      - API_KEY=$API_KEY
      - ZONE=$ZONE
      - SUBDOMAIN=$SUBDOMAIN
  cloudflare-ddns-ipv6:
    image: oznu/cloudflare-ddns
    container_name: cloudflare-ddns-ipv6
    restart: unless-stopped
    network_mode: host
    environment:
      - RRTYPE=AAAA
      - API_KEY=$API_KEY
      - ZONE=$ZONE
      - SUBDOMAIN=$SUBDOMAIN

  cloudflare-ddns-wildcard-ipv4:
    image: oznu/cloudflare-ddns
    container_name: cloudflare-ddns-wildcard-ipv4
    restart: unless-stopped
    network_mode: host
    environment:
      - RRTYPE=A
      - API_KEY=$API_KEY
      - ZONE=$ZONE
      - SUBDOMAIN=*.$SUBDOMAIN
  cloudflare-ddns-wildcard-ipv6:
    image: oznu/cloudflare-ddns
    container_name: cloudflare-ddns-wildcard-ipv6
    restart: unless-stopped
    network_mode: host
    environment:
      - RRTYPE=AAAA
      - API_KEY=$API_KEY
      - ZONE=$ZONE
      - SUBDOMAIN=*.$SUBDOMAIN
